version: "3"

services:
  web:
    build: .
    image: dataserver
    depends_on:
      - db
      - redis
    volumes:
      - .:/code
    command: ./manage.py runserver 0.0.0.0:8000
    stop_signal: SIGINT
    restart: always
    ports:
      - 18000:8000

  db:
    image: postgres:13
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/code
    environment:
      POSTGRES_USER: train
      POSTGRES_PASSWORD: train
      POSTGRES_DB: train
      PGTZ: Pacific/Auckland

  redis:
    image: redis
    restart: always

volumes:
  pgdata:
